issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
  - bodyclose
  - goconst
  - godot
  - godox
  - gofmt
  - goimports
  - revive
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - prealloc
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/remychantenay/slog-otel

run:
  timeout: 10m
  modules-download-mode: readonly
